### PR TITLE
Replace .rc script by .res resource file in order to avoid issues with windres 

### PR DESCRIPTION
**Pull request by wp-xyz**
Replace .rc script by .res resource file in order to avoid issues with windres (https://forum.lazarus.freepascal.org/index.php/topic,48691.msg350922.html).
Add additional high-dpi palette icons.

### CODE REVIEW

**Comment by dezlov** [comment]
Thanks for the changes. Looks good.

**Comment by dezlov** [comment]
For those encountering the same problem with `windres` prior to these changes, you need to replace `\` with `/` in the `*.rc` file to fix the issue.

**Comment by wp-xyz** [comment]
The new revision is not yet available through OPM. You should give the new version a new version number and pack the files into a zip in your "archive" like you did before. Then you should update the update.json file with the storage location of the new zip. This would make the new version available for OPM installation from the "third-party repository". In order to bring it into the "official repository" you should contact forum user GetMem, the maintainer of OPM, and ask him to update the package in OPM.

**Comment by dezlov** [comment]
I sent a message to GetMem asking to update the package in the OPM repository.

**Pull request merged**
